final
Anna-K-S/magic-8-ball pull request #1
Opened 2023-03-16 01:05 UTC by Anna-K-S

@feduke-nukem

https://user-images.githubusercontent.com/119135816/225483225-2ef70bfe-fb09-4e6e-a5b1-99b847dd48d1.mov

https://user-images.githubusercontent.com/119135816/225483353-7f26ffed-44a8-46d3-a8bb-d87c66573c01.mp4

2023-03-16 04:07 UTC, feduke-nukem requested changes

2023-03-16 04:07 UTC, feduke-nukem commented on lib/main.dart
> +  int ballNumber = 1;
Хорошо бы сделать приватным 
```dart
int ballNumber = 1;
```
в

```dart
int _ballNumber = 1;
```

2023-03-16 04:07 UTC, feduke-nukem commented on lib/main.dart
> +  void changeBallNumber() {
Тоже по приватности касатеся и метода

2023-03-16 04:10 UTC, feduke-nukem commented on lib/main.dart
> +              },
Вот такие вещи в Dart можно использовать так:

```dart
onPressed: changeBallNumber
```

Это называется `tear-off` функция.

Посмотреть можно [здесь](https://www.youtube.com/watch?v=OmCaloD7sis&ab_channel=Flutter) и [здесь](https://stackoverflow.com/questions/69065771/what-is-a-tear-off-tearoff-tear-off)

Грубо говоря, когда сигнатура функций совпадает, то их можно передавать просто как параметр без лишнего кода

2023-03-16 22:04 UTC, Anna-K-S commented on lib/main.dart
> +  int ballNumber = 1;
+

2023-03-16 22:09 UTC, Anna-K-S commented on lib/main.dart
> +              },
готово

2023-03-16 22:10 UTC, merged

2023-03-17 06:00 UTC, feduke-nukem commented on lib/main.dart
> +              onPressed: _changeBallNumber();
Необходимо сделать так 

из 
```dart
onPressed: _changeBallNumber()
```
в 

```dart
onPressed: _changeBallNumber
```

В конце нет скобок, просто название метода